### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Toxxi-frank** [DariusAf/MesoNet#29]
Hi, after downloading the dataset, I saw 2 folders named: train::test and validation. I know that the dataset usually must contain 3 parts: train-set, valid-set and test-set. 
I wonder how u use those 2 folders in training model and evaluate model.   

@DariusAf

**Comment by DariusAf** [comment]
Oh, it thought this had been corrected a long time ago, there was a misspell due to last minute formatting. The first folder is train + validation and the second is used for test afterwards. More details about data loading are discussed [in this issue](https://github.com/DariusAf/MesoNet/issues/4#issuecomment-448694527).
